// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ6lJbu_IqGm8zNeI-T-P-_TcgvyEx0LY',
    appId: '1:566388806760:android:7d8e4e0e97683f9ff917dd',
    messagingSenderId: '566388806760',
    projectId: 'ceng3006-c59d3',
    databaseURL: 'https://ceng3006-c59d3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ceng3006-c59d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc8IGJHJKQEdGojpEqbmuNd8WJEvdeFws',
    appId: '1:566388806760:ios:34cd36c33aaf921ff917dd',
    messagingSenderId: '566388806760',
    projectId: 'ceng3006-c59d3',
    databaseURL: 'https://ceng3006-c59d3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ceng3006-c59d3.appspot.com',
    iosClientId: '566388806760-5go808j3n35kghipaib1bta8qcc95a88.apps.googleusercontent.com',
    iosBundleId: 'com.example.embedded',
  );
}
